version: '2.1'
services:
  payment-service:
    image: 'payment-service:latest'
    build:
      context: ../payment-service
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    container_name: payment-service
    restart: always

  inventory-service:
    image: 'inventory-service:latest'
    build:
      context: ../inventory-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    container_name: inventory-service

  order-orchestrator:
    image: 'order-orchestrator:latest'
    build:
      context: ../order-orchestrator
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    container_name: order-orchestrator
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - inventory-service
      - payment-service
      - kafka

  order-service:
    image: 'order-service:latest'
    build:
      context: ../order-service
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    container_name: order-service
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1